project:
  type: website
  output-dir: docs

website:
  title: "CompEconUMN2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Julia Lectures
        menu:
          - text: "Lecture 1"
            href: Julia/Lectures/Julia_Lec_1_Compecon_Xing_Xu.ipynb
          - text: "Lecture 2"
            href: Julia/Lectures/Julia_Lec_2_Compecon_Xing_Xu.ipynb
          - text: "Lecture 3"
            href: Julia/Lectures/Julia_Lec_3_Compecon_Xing_Xu.ipynb
          - text: "Lecture 4"
            href: Julia/Lectures/Julia_Lec_4_Compecon_Xing_Xu.ipynb
          - text: "Lecture 5"
            href: Julia/Lectures/Julia_Lec_5_Compecon_Xing_Xu.ipynb
          - text: "Lecture 6"
            href: Julia/Lectures/Julia_Lec_6_Compecon_Xing_Xu.ipynb
      - text: Python Lectures
        menu:
          - text: "Lecture 1"
            href: Python/Lectures/lecture1.ipynb
          - text: "Lecture 2"
            href: Python/Lectures/lecture2.ipynb
          - text: "Lecture 3"
            href: Python/Lectures/lecture3.ipynb
          # - text: "Lecture 4"
          #   href: Python/Lectures/lecture4.ipynb
          # - text: "Lecture 5"
          #   href: Python/Lectures/lecture5.ipynb
      - text: Julia Assignments
        menu: 
          - text: "Assignment 1"
            href: Julia/Assignments/Julia_PS_1_Compecon_Xing_Xu.ipynb
          - text: "Assignment 2"
            href: Julia/Assignments/Julia_PS_2_Compecon_Xing_Xu.ipynb

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    toc: true